dev_model:
  catalog: scott_donohoo_dev
  schema: ml_ops_dabs
  model_name: iris_model
  model_alias: champion
endpoint_name: sdonohoo_ml_ops_dabs
prod_model:
  catalog: scott_donohoo_prod
  schema: ml_ops_dabs
  model_name: iris_model
  model_alias: champion